application: gettouchicon
version: 3
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: latest

handlers:
- url: .*
  script: getfvco.application
